# GitHub Actions Workflow for Continuous Integration (CI)
#
# This workflow automatically runs tests, linting, and type checks
# on pushes to main and on pull requests targeting main.
# It ensures that all code merged into main passes quality checks.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.11"]

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Install Nox and Poetry
      - name: Install Nox and Poetry
        run: python -m pip install nox poetry

      # Install Poetry export plugin
      - name: Install Poetry export plugin
        run: python -m poetry self add poetry-plugin-export

      # Run all Nox sessions for this Python version
      - name: Run Nox sessions
        run: nox -p ${{ matrix.python-version }}
